### PR TITLE
added Rx, Ry and Rz gates

### PR DESCRIPTION
**Pull request by atwupack**
Hi, I needed the Rx gate for an example and noticed that the three rotational gates Rx, Ry and Rz are currently missing. So, I added them to the builder.
I have only tested the Rx gate. Please check if they are all correct.

André

### CODE REVIEW

**Comment by atwupack** [comment]
I am currently replacing some of the existing code with the new gates. This PR should stay open until this has been completed.

**Comment by atwupack** [comment]
This should be it. The PR is now ready if you want to merge it.

**Comment by Renmusxd** [comment]
Great, I should be able to check this out on Saturday and merge it in. Thanks for the help!

**Comment by Renmusxd** [comment]
Using the gates in the teleport test seems like a good test to me, it's just reusing the existing real_mat operation with pauli matrices. I don't think additional unit tests are necessary. Thanks!

**Pull request merged**
